http:
  routers:
    ss-poc-ui:
      rule: Host(`app.localhost`) || Host(`app.poc.localhost`)
      entryPoints:
        - web
      service: ss-poc-ui

  services:
    ss-poc-ui:
      loadBalancer:
        servers:
          - url: http://ss-poc-ui-blazor-ui:8080
